# pandas - "A melhor biblioteca do Python para Dados"

- Quase sempre que você for trabalhar com dados no Python você vai usar o pandas, então é importante você saber trabalhar com essa biblioteca muito bem

- Vamos aprender os principais comandos e os princípios básicos do pandas

- Faça o download do Gabarito desse arquivo e use como uma cartilha de consulta (Link na descrição)

### Importando o pandas

In [4]:
import pandas as pd # pd = pandas

### Criando um dataframe a partir de um dicionário

In [5]:
# dataframe = pd.DataFrame()
venda = {'data': ['15/02/2021', '16/02/2021'],
         'valor': [500, 300],                                     # isso aqui é oque criamos , ja esta tudo atribuido como vendas.
         'produto': ['feijao', 'arroz'],
         'qtde': [50, 70],
        }
vendasDF = pd.DataFrame(venda) #DF = DATA FRAME

### Visualização dos Dados
    - print
    - display

In [6]:
display (vendasDF)
# print (vendasDF)   da pra vizualizar assim.

         data  valor produto  qtde
0  15/02/2021    500  feijao    50
1  16/02/2021    300   arroz    70

### Importando arquivos e bases de dados

In [7]:
#vamos importar de uma base de dados, no caso um arquivo excel
vendasDF = pd.read_excel("Vendas.xlsx")
display(vendasDF)
#rows = linhas  - coluns = colunas

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

### Resumos de Visualização de Dados simples e úteis
    - head
    - shape
    - describe

In [8]:
display(vendasDF.head(6))   # o metodo ❗HEAD❗ aqui mostra a cabeça da nossa tabela, o numero dentro é ate qual numero irá mostrar
display(vendasDF.tail(6))   # o metodo ❗TAIL❗ aqui vemos o cauda, ou seja o final.
                            # poderia ser print ao invez de display, mas o display mostra bem mais organizado. 
display(vendasDF.shape)     # o método ❗SHAPE❗, a gente vê quantas linhas tem e quantas colunas
display(vendasDF.describe())# o metodo ❗DESCRIBE❗faz um resumo, mosstra em média os dados, m´pedia de valores, unidades vendidas e tal.

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
93904,65012,2019-11-30,Shopping Vila Velha,Bermuda Liso,4,157,628
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

(93910, 7)

,Código Venda,Data,Quantidade,Valor Unitário,Valor Final
count,93910.000000,93910,93910.000000,93910.000000,93910.000000
mean,32464.762155,2019-06-16 23:52:28.265360896,2.166553,191.725886,414.862656
min,1.000000,2019-01-01 00:00:00,1.000000,30.000000,30.000000
25%,16204.000000,2019-03-26 00:00:00,1.000000,100.000000,156.000000
50%,32367.000000,2019-06-17 00:00:00,2.000000,155.000000,274.000000
75%,48793.750000,2019-09-08 00:00:00,3.000000,248.000000,524.000000
max,65014.000000,2019-11-30 00:00:00,5.000000,750.000000,3750.000000
std,18809.007093,NaN,1.258732,145.215519,434.846228

### Pegar 1 coluna (e os pd.Series)

In [17]:
#como  pegar uma coluna e isolar a vizualização de dadpos focado nela?
produtos = vendasDF[["Data","ID Loja","Produto"]] #iremos criar a variavel no caso colocamos o mesmo nome da coluna que queremos, BASICAMENTE DIZENDO, que a variavel que estamos criando é = pra entrar dentrro de VENDASDF e pegar la dentro "Produto", dai salva na memória.
display(produtos) # não vai aparecer em formato DISPLAY, porque é uma coluna só, e ai mnostra uma ✨SERIE de pandas.

# para ler mais de uma coluna, repare que temos que colocar UMA chave, se ão não da certo

            Data              ID Loja            Produto
0     2019-01-01   Iguatemi Esplanada     Sapato Estampa
1     2019-01-01   Iguatemi Esplanada           Camiseta
2     2019-01-01   Iguatemi Esplanada      Sapato Xadrez
3     2019-01-02       Norte Shopping            Relógio
4     2019-01-02       Norte Shopping       Chinelo Liso
...          ...                  ...                ...
93905 2019-11-30  Shopping Vila Velha     Mochila Xadrez
93906 2019-11-30    Ribeirão Shopping  Pulseira Listrado
93907 2019-11-30    Ribeirão Shopping     Cueca Listrado
93908 2019-11-30     Shopping Morumbi     Pulseira Linho
93909 2019-11-30     Shopping Morumbi      Casaco Xadrez

[93910 rows x 3 columns]

### .loc, um método muito importante
    - Pegar 1 linha
    - Pegar linhas de acordo com alguma condição
    - Pegar linhas e colunas específicas
    - Pegar 1 valor específico

In [ ]:
#como pegar uma linha especifica?
display(vendasDF.loc[0]) #basicamente isso, e nas chaves vc adiciona a linha, pelo INDICE, que é a primeira coluna.

Código Venda                        1
Data              2019-01-01 00:00:00
ID Loja            Iguatemi Esplanada
Produto                Sapato Estampa
Quantidade                          1
Valor Unitário                    358
Valor Final                       358
Name: 0, dtype: object

In [26]:
display(vendasDF.loc[0:5]) # aqui eu poderia taambém pegar mais de uma linha, por exemplo ✨ usando os dois pontos ":" ✨

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248

In [ ]:
display(vendasDF.loc[vendasDF["ID Loja"] == "Iguatemi Esplanada"]) # aqui entramos na coluna, ID LOJAS e filtramos todas as vezes que é IGUAL a 'iguatemi Esplanda

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
26,21,2019-01-02,Iguatemi Esplanada,Camisa Gola V Listrado,2,116,232
44,34,2019-01-02,Iguatemi Esplanada,Sapato Listrado,1,363,363
...,...,...,...,...,...,...,...
93745,64908,2019-11-30,Iguatemi Esplanada,Meia,4,30,120
93776,64928,2019-11-30,Iguatemi Esplanada,Tênis Xadrez,3,259,777
93880,64993,2019-11-30,Iguatemi Esplanada,Bermuda Liso,2,157,314
93881,64993,2019-11-30,Iguatemi Esplanada,Chinelo Xadrez,1,66,66
93882,64993,2019-11-30,Iguatemi Esplanada,Cinto Liso,1,209,209

In [ ]:
display(vendasDF.loc[vendasDF["Produto"] == "Relógio"]) # filtramos aqui nma coluna produtos e tudo que fosse igual a rélogio ele filtrou.

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
46,35,2019-01-02,Parque Dom Pedro Shopping,Relógio,2,200,400
50,38,2019-01-02,Shopping Vila Velha,Relógio,1,200,200
96,71,2019-01-02,Shopping Iguatemi Fortaleza,Relógio,4,200,800
259,186,2019-01-02,Parque Dom Pedro Shopping,Relógio,4,200,800
...,...,...,...,...,...,...,...
93546,64757,2019-11-29,Iguatemi Esplanada,Relógio,2,200,400
93630,64825,2019-11-30,Bourbon Shopping SP,Relógio,3,200,600
93706,64881,2019-11-30,Shopping Center Interlagos,Relógio,1,200,200
93778,64929,2019-11-30,Shopping União de Osasco,Relógio,2,200,400
93791,64937,2019-11-30,Parque Dom Pedro Shopping,Relógio,1,200,200

In [38]:
#pegar varias linhas e colunas usando o loc
vendasIguatemi = vendasDF.loc[vendasDF["ID Loja"] == "Iguatemi Esplanada",["ID Loja","Produto","Quantidade"]]  # aqui definimos que a variavel "vendasIguatemi" é a tabela filtrada para mostrar somente as vendas dessa loja.
display(vendasIguatemi)

                  ID Loja                 Produto  Quantidade
0      Iguatemi Esplanada          Sapato Estampa           1
1      Iguatemi Esplanada                Camiseta           2
2      Iguatemi Esplanada           Sapato Xadrez           1
26     Iguatemi Esplanada  Camisa Gola V Listrado           2
44     Iguatemi Esplanada         Sapato Listrado           1
...                   ...                     ...         ...
93745  Iguatemi Esplanada                    Meia           4
93776  Iguatemi Esplanada            Tênis Xadrez           3
93880  Iguatemi Esplanada            Bermuda Liso           2
93881  Iguatemi Esplanada          Chinelo Xadrez           1
93882  Iguatemi Esplanada              Cinto Liso           1

[3722 rows x 3 columns]

In [42]:
#PEGAR UM VALOR ESPECÍFICO.

#print(vendasDF[linha,coluna])
print(vendasDF.loc[46,"Produto"]) # tem que voltar relogio

Relógio

### Adicionar 1 coluna

In [ ]:
#adicionar coluna nova, apartir de uma coluna que ja existe, usamos uma que existe para criar uma nova... exemplo:
vendasDF["Comissão"] = vendasDF["Valor Final"] * 0.05 # pega o valor fiunal da vendasdf e mulçtiplica para criar uma variavel comissão
display(vendasDF)
#veja que criou a tabela comissão apartir da coluna valor final!

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55
...,...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566,28.30
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158,7.90
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201,10.05
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570,28.50
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036,51.80

In [61]:
#agora vamos criar uma coluna totalmente do zero,
#vendasDF.loc[linha,coluna] = 0
vendasDF.loc[:,"imposto"] = 0 #quando adicionamos dois pontos aqui, quer dizer que o valor 0 vai ser em ✨todas as linhas✨.
display(vendasDF)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão,imposto
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90,0
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00,0
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40,0
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00,0
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55,0
...,...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,NaN,0
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,NaN,0
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,NaN,0
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,NaN,0
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,NaN,0

### Adicionar 1 linha
    - Linhas de um complemento da base de dados

In [59]:
#como adicionar linha no nosso data frame
vendasDezembroDF = pd.read_excel("Vendas - Dez.xlsx") #importa arquivo de vendas dezembro para codigo.
display(vendasDezembroDF)

vendasDF = pd.concat([vendasDF, vendasDezembroDF]) # aqui adiciona como apendice os dados da variavel que criei , as vendas de dezembro
display(vendasDF)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
3,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
4,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276
...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55
...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,NaN
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,NaN
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,NaN
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,NaN
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,NaN

### Excluir linhas e colunas

In [ ]:
vendasDF = vendasDF.drop("imposto",axis = 1) # eixo = 0 linha, eixo = 1 coluna
display(vendasDF)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55
...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,NaN
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,NaN
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,NaN
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,NaN
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,NaN

### Valores Vazios
    - Deletar linhas/colunas vazias
    - Deletar linhas que possuem valores vazios
    - Preencher valores vazios (média e último valor)

In [ ]:
#metodo de exluir linhas e colunas vazios vazios NAN
vendasDF = vendasDF.dropna(how="all",axis=1) #aqui basicamente exlui a coluna toda, se tiver tudo vazio.

In [ ]:
#deletar linhas que possuem pelo menos 1 valor vazio
vendasDF = vendasDF.dropna() #sem inserir paramentro ja faz oque queremos.

In [ ]:
#preencer com a média da coluna
vendasDF['Comissão'] = vendasDF ["Comissão"].fillna(vendasDF["Comissão"].mean())

# acessa dataframe entrando na coluna comissão, onde  define essa coluna novamente fazendo com que dessa vez "fillna" ou seja ppreencha os valores vazios com  o valor da MÉDIA(mean) da comissao - FORMA MAIS USADA DE PREENCHER
display(vendasDF)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.900000
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.000000
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.400000
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.000000
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.550000
...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,20.743133
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,20.743133
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,20.743133
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,20.743133
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,20.743133

In [65]:
#preencher com o ultimo valor
vendasDF = vendasDF.ffill()
display(vendasDF)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.900000
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.000000
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.400000
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.000000
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.550000
...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,20.743133
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,20.743133
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,20.743133
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,20.743133
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,20.743133

### Calcular Indicadores
    - Groupby
    - Value Counts

In [ ]:
transacoesLojas = vendasDF["ID Loja"].value_counts()
display(transacoesLojas)

#basicamente faz a contagem, no caso a quantidade de transições

ID Loja
Shopping Vila Velha                 4832
Rio Mar Recife                      4831
Palladium Shopping Curitiba         4812
Iguatemi Campinas                   4738
Rio Mar Shopping Fortaleza          4706
Norte Shopping                      4689
Bourbon Shopping SP                 4688
Salvador Shopping                   4634
Shopping SP Market                  4624
Center Shopping Uberlândia          4613
Shopping Eldorado                   4610
Ribeirão Shopping                   4602
Shopping Iguatemi Fortaleza         4601
Shopping Ibirapuera                 4597
Passei das Águas Shopping           4578
Shopping Morumbi                    4572
Shopping União de Osasco            4563
Shopping Center Leste Aricanduva    4553
Shopping Center Interlagos          4529
Novo Shopping Ribeirão Preto        4527
Iguatemi Esplanada                  4496
Parque Dom Pedro Shopping           4482
Shopping Barra                      4482
Shopping Recife                     4463
Shopping Midway Mall                4355
Name: count, dtype: int64

In [67]:
#agrupa informações

#ele vai agrupar e somar, nesse exemplo , ele vbai agrupar todos itens chamados camisas e somar os valores.

# faturamentoProduto = vendasDF.groupby("coluna") 
faturamentoProduto = vendasDF.groupby("Produto").sum()

#pega o vendasDF, vai agrupar a coluna de produtos( aparecer um produto só em cada linha) e somar as colunas numéricas

display(faturamentoProduto)

TypeError: datetime64 type does not support sum operations

### Mesclar 2 dataframes (Procurar informações de um dataframe em outro)

### Como continuar aprendendo?

### Minicurso Gratuito de Análise de Dados com Python na Descrição