# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [1]:
import pandas as pd
import numpy as np

In [ ]:
from numpy.random import randn
np.random.seed(101) #quantas funções random tem em numpy = 3 randInt,randN,rand

In [44]:
df = pd.DataFrame(data=randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split()) # pd = pandas.
#data= matriz 5 linhas 4 colunas.
#split= quebra no espaço ao invez de virgula.
#df= definimos o valor de df = DataFrame.

In [45]:
df

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [27]:
df.pop('W')

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [39]:
df

                          NEW
X         Y
 1.693723 -1.706086 -0.012363
 0.390528  0.166905  0.557432
 0.072960  0.638787  0.711747
-0.754070 -0.943406 -1.697476
 1.901755  0.238127  2.139882

In [46]:
df.pop('Z')

A    0.000366
B    0.649826
C   -0.346419
D    1.024810
E    0.610478
Name: Z, dtype: float64

In [47]:
df

          W         X         Y
A -0.993263  0.196800 -1.136645
B  1.025984 -0.156598 -0.031579
C  2.154846 -0.610259 -0.755325
D  0.147027 -0.479448  0.558769
E -0.925874  1.862864 -1.133817

In [48]:
df['NEW'] = df['X']+df['Y']
df

          W         X         Y       NEW
A -0.993263  0.196800 -1.136645 -0.939845
B  1.025984 -0.156598 -0.031579 -0.188177
C  2.154846 -0.610259 -0.755325 -1.365584
D  0.147027 -0.479448  0.558769  0.079321
E -0.925874  1.862864 -1.133817  0.729047

In [32]:
df.set_index(['X','Y'],inplace=True)
df

                          NEW
X         Y
 1.693723 -1.706086 -0.012363
 0.390528  0.166905  0.557432
 0.072960  0.638787  0.711747
-0.754070 -0.943406 -1.697476
 1.901755  0.238127  2.139882

In [33]:
tabela = df['NEW'].unstack('Y')
tabela

Y          -1.706086  -0.943406   0.166905   0.238127   0.638787
X
-0.754070        NaN  -1.697476        NaN        NaN        NaN
 0.072960        NaN        NaN        NaN        NaN   0.711747
 0.390528        NaN        NaN   0.557432        NaN        NaN
 1.693723  -0.012363        NaN        NaN        NaN        NaN
 1.901755        NaN        NaN        NaN   2.139882        NaN

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [ ]:
df['W']

In [ ]:
df[['W','Z']]

In [ ]:
# Pass a list of column names
df[['W','Z']]

In [ ]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

DataFrame Columns are just Series

In [ ]:
type(df['W'])

**Creating a new column:**

In [ ]:
df['new'] = df['W'] + df['Y']

In [ ]:
df

** Removing Columns**

In [ ]:
df.drop('W',axis=1)

In [ ]:
df

In [ ]:
# Not inplace unless specified!
df

In [ ]:
df.drop('new',axis=1,inplace=True)

In [ ]:
df

Can also drop rows this way:

In [ ]:
df.drop('E',axis=0)

In [ ]:
df

In [ ]:
df.drop('E')

In [ ]:
df

In [ ]:
df.iloc[3][2]

** Selecting Rows**

In [ ]:
df.loc['A']

Or select based off of position instead of label

In [ ]:
df.iloc[0]

In [ ]:
df.iloc[2][1]

** Selecting subset of rows and columns **

In [ ]:
df.loc['B','Y']

In [ ]:
df.loc[['A','B'],['W','Y']]

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [ ]:
df

In [ ]:
df>0

In [ ]:
df[df>0]

In [ ]:
df[df['W']>0]

In [ ]:
df

In [ ]:
df[df['W']>0]['Y']

In [ ]:
df[df['W']>0][['Y','X']]

In [ ]:
df

For two conditions you can use | and & with parenthesis:

In [ ]:
df[(df['W']>0) & (df['Y'] > 1)]

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [ ]:
df

In [ ]:
# Reset to default 0,1...n index
df.reset_index()

In [ ]:
newdata = 'CA NY WY OR CO'.split()

In [ ]:
newdata

In [ ]:
df['States'] = newdata

In [ ]:
df

In [ ]:
df.set_index('States')

In [ ]:
df

In [ ]:
df.set_index('States',inplace=True)

In [ ]:
df

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [ ]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']

inside = [1,2,3,4,5,6]

hier_index = list(zip(outside,inside))

hier_index = pd.MultiIndex.from_tuples(hier_index)

In [ ]:
hier_index

In [ ]:
df1 = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])

In [ ]:
df1

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [ ]:
df1.loc['G1']

In [ ]:
df1.loc['G1'].loc[1]

In [ ]:
df1.index.names

In [ ]:
df1.index.names = ['Group','Numbers']

In [ ]:
df1

In [ ]:
df1

In [ ]:
df1.loc['G1']

In [ ]:
df1.xs('G1')

In [ ]:
df1.xs(('G1',1))

In [ ]:
df1

In [ ]:
df1.xs(5,level='Numbers')