# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [1]:
import pandas as pd
import numpy as np

In [2]:
from numpy.random import randn
np.random.seed(101) #quantas funções random tem em numpy = 3 randInt,randN,rand

In [9]:
df = pd.DataFrame(data=randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split()) # pd = pandas.
#data= matriz 5 linhas 4 colunas.
#split= quebra no espaço ao invez de virgula.
#df= definimos o valor de df = DataFrame.

In [10]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [11]:
df.pop('W')

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [13]:
df

          X         Y         Z
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965
C  0.740122  0.528813 -0.589001
D -0.758872 -0.933237  0.955057
E  1.978757  2.605967  0.683509

In [14]:
df.pop('Z')

A    0.503826
B    0.605965
C   -0.589001
D    0.955057
E    0.683509
Name: Z, dtype: float64

In [15]:
df

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
C  0.740122  0.528813
D -0.758872 -0.933237
E  1.978757  2.605967

In [16]:
df['NEW'] = df['X']+df['Y']
df

          X         Y       NEW
A  0.628133  0.907969  1.536102
B -0.319318 -0.848077 -1.167395
C  0.740122  0.528813  1.268936
D -0.758872 -0.933237 -1.692109
E  1.978757  2.605967  4.584725

In [17]:
df.set_index(['X','Y'],inplace=True)
df

                          NEW
X         Y
 0.628133  0.907969  1.536102
-0.319318 -0.848077 -1.167395
 0.740122  0.528813  1.268936
-0.758872 -0.933237 -1.692109
 1.978757  2.605967  4.584725

In [18]:
tabela = df['NEW'].unstack('Y')
tabela

Y          -0.933237  -0.848077   0.528813   0.907969   2.605967
X
-0.758872  -1.692109        NaN        NaN        NaN        NaN
-0.319318        NaN  -1.167395        NaN        NaN        NaN
 0.628133        NaN        NaN        NaN   1.536102        NaN
 0.740122        NaN        NaN   1.268936        NaN        NaN
 1.978757        NaN        NaN        NaN        NaN   4.584725

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [21]:
df['W']

KeyError: 'W'

In [ ]:
df[['W','Z']]

In [ ]:
# Pass a list of column names
df[['W','Z']]

In [ ]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

DataFrame Columns are just Series

In [ ]:
type(df['W'])

**Creating a new column:**

In [ ]:
df['new'] = df['W'] + df['Y']

In [ ]:
df

** Removing Columns**

In [ ]:
df.drop('W',axis=1)

In [ ]:
df

In [ ]:
# Not inplace unless specified!
df

In [ ]:
df.drop('new',axis=1,inplace=True)

In [ ]:
df

Can also drop rows this way:

In [ ]:
df.drop('E',axis=0)

In [ ]:
df

In [ ]:
df.drop('E')

In [ ]:
df

In [ ]:
df.iloc[3][2]

** Selecting Rows**

In [ ]:
df.loc['A']

Or select based off of position instead of label

In [ ]:
df.iloc[0]

In [ ]:
df.iloc[2][1]

** Selecting subset of rows and columns **

In [ ]:
df.loc['B','Y']

In [ ]:
df.loc[['A','B'],['W','Y']]

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [ ]:
df

In [ ]:
df>0

In [ ]:
df[df>0]

In [ ]:
df[df['W']>0]

In [ ]:
df

In [ ]:
df[df['W']>0]['Y']

In [ ]:
df[df['W']>0][['Y','X']]

In [6]:
df

NameError: name 'df' is not defined

For two conditions you can use | and & with parenthesis:

In [5]:
df[(df['W']>0) & (df['Y'] > 1)]

NameError: name 'df' is not defined

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [4]:
df

NameError: name 'df' is not defined

In [ ]:
# Reset to default 0,1...n index
df.reset_index()

In [ ]:
newdata = 'CA NY WY OR CO'.split()

In [ ]:
newdata

In [ ]:
df['States'] = newdata

In [ ]:
df

In [ ]:
df.set_index('States')

In [ ]:
df

In [ ]:
df.set_index('States',inplace=True)

In [ ]:
df

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [ ]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2'] # outside- o mais externo

inside = [1,2,3,4,5,6]

hier_index = list(zip(outside,inside))

hier_index = pd.MultiIndex.from_tuples(hier_index)

In [23]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 4),
            ('G2', 5),
            ('G2', 6)],
           )

In [24]:
df1 = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])

In [25]:
df1

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 4  0.166905  0.184502
   5  0.807706  0.072960
   6  0.638787  0.329646

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [ ]:
df1.loc['G1'] #localiza especificamente oque esta definido no index

          A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [27]:
df1.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [28]:
df1.index.names

FrozenList([None, None])

In [29]:
df1.index.names = ['Group','Numbers']

In [30]:
df1

                      A         B
Group Numbers
G1    1        0.302665  1.693723
      2       -1.706086 -1.159119
      3       -0.134841  0.390528
G2    4        0.166905  0.184502
      5        0.807706  0.072960
      6        0.638787  0.329646

In [31]:
df1

                      A         B
Group Numbers
G1    1        0.302665  1.693723
      2       -1.706086 -1.159119
      3       -0.134841  0.390528
G2    4        0.166905  0.184502
      5        0.807706  0.072960
      6        0.638787  0.329646

In [32]:
df1.loc['G1']

                A         B
Numbers
1        0.302665  1.693723
2       -1.706086 -1.159119
3       -0.134841  0.390528

In [ ]:
df1.xs('G1') #mais atual

                A         B
Numbers
1        0.302665  1.693723
2       -1.706086 -1.159119
3       -0.134841  0.390528

In [35]:
df1.xs(('G1',1))

A    0.302665
B    1.693723
Name: (G1, 1), dtype: float64

In [36]:
df1

                      A         B
Group Numbers
G1    1        0.302665  1.693723
      2       -1.706086 -1.159119
      3       -0.134841  0.390528
G2    4        0.166905  0.184502
      5        0.807706  0.072960
      6        0.638787  0.329646

In [37]:
df1.xs(5,level='Numbers')

              A        B
Group
G2     0.807706  0.07296